version: 2.1

orbs:
  node: circleci/node@5.1.0
  sonarcloud: sonarsource/sonarcloud@2.0.0

jobs:
  install:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - node/install:
          install-yarn: true
          node-version: "20"
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines
  build:
    docker:
      - image: cimg/base:stable
    environment:
      NEXT_PUBLIC_GA_MEASUREMENT_ID: sundayx/todo-api
      NEXT_PUBLIC_CMS_URL: latest
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: asd
    steps:
      - checkout
      - run:
          name: Build Packages
          command: yarn build
  analyze:
    docker:
      - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: Analyze Code
          command: sonarcloud/scan

workflows:
  install:
    jobs:
      - install
  build:
    jobs:
      - build
  analyze:
    jobs:
      - analyze
