version: 2.1

orbs:
  sonar: sonarsource/sonarcloud@2.0.0

jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    docker:
      - image: cimg/node:lts
    environment:
      NEXT_PUBLIC_GA_MEASUREMENT_ID: test
      NEXT_PUBLIC_CMS_URL: test
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: test
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Build Packages
          command: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  analyze:
    docker:
      - image: cimg/node:lts
    steps:
      - attach_workspace:
          at: .
      - run:
          name: Analyze Code
          command: sonar/scan

workflows:
  ci:
    jobs:
      - install
      - build:
          requires:
            - install
      - analyze:
          requires:
            - build
