version: 2.1

orbs:
  sonar: sonarsource/sonarcloud@2.0.0

jobs:
  install:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Install Dependencies
          command: yarn install --ignore-engines
  build:
    docker:
      - image: cimg/node:lts
    environment:
      NEXT_PUBLIC_GA_MEASUREMENT_ID: sundayx/todo-api
      NEXT_PUBLIC_CMS_URL: latest
      NEXT_PUBLIC_CLOUDINARY_CLOUD_NAME: asd
    steps:
      - checkout
      - run:
          name: Build Packages
          command: yarn build
  analyze:
    docker:
      - image: cimg/node:lts
    steps:
      - checkout
      - run:
          name: Analyze Code
          command: sonar/scan

workflows:
  ci:
    jobs:
      - install
      - build:
          requires:
            - install
      - analyze:
          requires:
            - build
